# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Make a Symmetric Cube
#'
#' This function makes a lower-triangular cube symmetric over the z-axis.
#' It was written to remove the dependency "Matrix".
#' It is only used in building cubes.
#'
#' @param lowerMat A lower-triangular matrix of depth 1 or more
#'
#' @export
SymCubeC <- function(lowerMat) {
    invisible(.Call('_MGDrivE_SymCubeC', PACKAGE = 'MGDrivE', lowerMat))
}

#' Shift a Vector
#'
#' Shift a population vector by one day and insert the new population.
#' This was written to remove the dependency "binhf".
#'
#' @param popVector List of population vectors of length(Tegg+Tlarva+Tpupa)
#' @param newPop Vector of length equal to the number of genotypes
#'
#' @export
shiftAndUpdatePopVector <- function(popVector, newPop) {
    invisible(.Call('_MGDrivE_shiftAndUpdatePopVector', PACKAGE = 'MGDrivE', popVector, newPop))
}

#' Dirichlet Distribution
#'
#' Make a single draw from a dirichlet distribution with the shape parameter
#' one. This replaces the MCMCpack rDirichlet function, which was wholly written
#' in R.
#'
#' @param migrationPoint Vector of weights for draws. Must be positive.
#'
#' @export
rDirichlet <- function(migrationPoint) {
    .Call('_MGDrivE_rDirichlet', PACKAGE = 'MGDrivE', migrationPoint)
}

#' Quantiles Function
#'
#' Calculate the given quantiles of a matrix.
#'
#' @usage quantileC(Trials, Probs)
#'
#' @param Trials Integer matrix to calculate quantiles over
#' @param Probs Vector of quantiles
#'
#' @details This function calculates the given quantiles over the rows of an
#' integer matrix. It uses method 8 of the stat::quantiles() function. It gives
#' the same result, to numerical accuracy, and is designed to handle matrix input.
#' It is only designed to work on integer matrices!
#'
#' @return Numeric Matrix
#'
#' @examples
#' Trials <- matrix(data = sample(x=1:100, size = 150, replace = TRUE), nrow=15, ncol=10)
#' DrawSize <- c(.25, .5, .75)
#'
#' quantileC(Trials, Probs)
#'
#' @export
quantileC <- function(Trials, Probs) {
    .Call('_MGDrivE_quantileC', PACKAGE = 'MGDrivE', Trials, Probs)
}

#' Calculate Haversine Distance
#'
#' Calculate the great-circle distance (Haversine distance) between sets of longitude - latitude points, see \url{https://en.wikipedia.org/wiki/Haversine_formula}
#'
#' @param longlats numeric matrix where first column is vector of longitudes and second column is vector of latitudes
#'
#' @export
calc_haversine <- function(longlats) {
    .Call('_MGDrivE_calc_haversine', PACKAGE = 'MGDrivE', longlats)
}

#' Calculate Lognormal Stochastic Matrix
#'
#' Given a distance matrix from \code{\link[MGDrivE]{calc_haversine}}, calculate a stochastic matrix where one step movement probabilities follow a lognormal density.
#'
#' @param distMat distance matrix from \code{\link[MGDrivE]{calc_haversine}}
#' @param meanlog log mean of \code{\link[stats]{Lognormal}} distribution
#' @param sdlog log standard deviation of \code{\link[stats]{Lognormal}} distribution
#'
#' @export
calc_LognormalKernel <- function(distMat, meanlog, sdlog) {
    .Call('_MGDrivE_calc_LognormalKernel', PACKAGE = 'MGDrivE', distMat, meanlog, sdlog)
}

#' Calculate Gamma Stochastic Matrix
#'
#' Given a distance matrix from \code{\link[MGDrivE]{calc_haversine}}, calculate a stochastic matrix where one step movement probabilities follow a gamma density.
#'
#' @param distMat distance matrix from \code{\link[MGDrivE]{calc_haversine}}
#' @param shape shape parameter of \code{\link[stats]{GammaDist}} distribution
#' @param rate rate parameter of \code{\link[stats]{GammaDist}} distribution
#'
#' @export
calc_GammaKernel <- function(distMat, shape, rate) {
    .Call('_MGDrivE_calc_GammaKernel', PACKAGE = 'MGDrivE', distMat, shape, rate)
}

#' Calculate Exponential Stochastic Matrix
#'
#' Given a distance matrix from \code{\link[MGDrivE]{calc_haversine}}, calculate a stochastic matrix where one step movement probabilities follow an exponential density.
#'
#' @param distMat distance matrix from \code{\link[MGDrivE]{calc_haversine}}
#' @param r rate parameter of \code{\link[stats]{Exponential}} distribution
#'
#' @export
calc_ExpKernel <- function(distMat, r) {
    .Call('_MGDrivE_calc_ExpKernel', PACKAGE = 'MGDrivE', distMat, r)
}

#' Calculate Hurdle Exponential Stochastic Matrix
#'
#' Given a distance matrix from \code{\link[MGDrivE]{calc_haversine}}, calculate a stochastic matrix where one step movement probabilities follow an zero-truncated exponential density with a point mass at zero.
#'
#' @param distMat distance matrix from \code{\link[MGDrivE]{calc_haversine}}
#' @param r rate parameter of \code{\link[stats]{Exponential}} distribution
#' @param pi point mass at zero
#'
#' @export
calc_HurdleExpKernel <- function(distMat, r, pi) {
    .Call('_MGDrivE_calc_HurdleExpKernel', PACKAGE = 'MGDrivE', distMat, r, pi)
}

